version: '3.8'

services:

  traefik:
    image: traefik:v2.3
    # mode=host required to get the correct client IP without further rules
    # also ports published by docker don't need to be opened in UFW because
    # docker adds the iptable rules automatically
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      placement:
        constraints: [node.role==manager]
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the volume to store the certificates
      - ${CONTAINER_DATA}/traefik:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_MAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # @todo disable?
      - --log
    networks:
      - traefik-net

  # this is the server we use for reading & writing from applications
  # it is placed on the swarm master for fast filesystem access
  # instead of relying on GlusterFS
  dbmaster:
    image: bitnami/mariadb:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
    volumes:
      # @todo is the attached storage fast enough? Or should the local SSD be used?
      - ${CONTAINER_DATA}/database0/db:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_pw
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  # the slave is only used for backups to that using mysqldump does not
  # lock tables too long for the applications
  dbslave:
    image: bitnami/mariadb:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==worker]
    volumes:
      # the replicated databases don't need to be stored on the
      # network filesystem. This will cause the slave to read the
      # whole binlog again when the swarm switches it to another node.
      - /opt/container-data/dbslave:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_pw
      - MARIADB_MASTER_HOST=dbmaster
      # used to access the master, also set as local root pw
      - MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  website:
    image: nginx
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-net-http.rule=Host(`test.vrok.de`)
        - traefik.http.routers.traefik-net-http.entrypoints=http
        - traefik.http.routers.traefik-net-http.middlewares=https-redirect
        - traefik.http.routers.traefik-net-https.rule=Host(`test.vrok.de`)
        - traefik.http.routers.traefik-net-https.entrypoints=https
        - traefik.http.routers.traefik-net-https.tls=true
        - traefik.http.routers.traefik-net-https.tls.certresolver=le
        - traefik.http.services.traefik-net.loadbalancer.server.port=80
    volumes:
      - /var/www/html/index.html:/usr/share/nginx/html/index.html
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
